version: "3.9"

volumes:
  psql:
  caddy-config:
  caddy-data:

services:
  psql:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  museo:
    build: .
    depends_on:
      - psql
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=production
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}?schema=public

  caddy:
    container_name: caddy
    image: caddy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy:/usr/share/caddy
